* dotfiles

** Chrome

[[https://www.if-not-true-then-false.com/2010/install-google-chrome-with-yum-on-fedora-red-hat-rhel/]]

Basically

#+BEGIN_SRC bash
sudo dnf install fedora-workstation-repositories
sudo dnf config-manager --set-enabled google-chrome
sudo dnf install google-chrome-stable
#+END_SRC

** Just

#+BEGIN_SRC bash :noeval
just --completions bash | sudo tee /etc/bash_completion.d/just > /dev/null
#+END_SRC

** Docker

For new versions if Fedora (>= 32): https://docs.docker.com/engine/install/fedora/

So you don't have to write ~sudo~ before every ~docker~ command add you user to
a docker group (suggested when starting ~minikube~):

#+BEGIN_SRC bash
sudo usermod -aG docker $USER && newgrp docker
#+END_SRC

For older versions (<= 31):

[[https://linuxconfig.org/how-to-install-docker-on-fedora-31]]

There is a problem that you can't run docker in fedora 31 due to CGroupsV2

This thread has some information how to solve it:

https://www.reddit.com/r/linuxquestions/comments/dn2psl/upgraded_to_fedora_31_docker_will_not_work/

*** Kubectl

https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

To activate bash auto completion

#+BEGIN_SRC bash
kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
#+END_SRC

*** Minikube

https://minikube.sigs.k8s.io/docs/start/

#+BEGIN_SRC bash
minikube config set driver docker
minikube start

# Verify that it started and we can connect
kubectl cluster-info

# See dashboard
minikube dashboard
#+END_SRC

*** Helm

Install helm: https://helm.sh/docs/intro/install/

#+BEGIN_SRC bash
# Needed for verification during running get_helm.sh
sudo dnf install openssl

curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh
#+END_SRC

** Install Java

https://phoenixnap.com/kb/fedora-install-java

To install latest (see version in the description when searching):

#+BEGIN_SRC bash
dnf search openjdk
sudo dnf install java-latest-openjdk-devel.x86_64
#+END_SRC

#+BEGIN_SRC bash
# These steps isn't necessary it seems. Also the path is probably wrong
sudo update-alternatives --install "/usr/bin/java" "java" "/usr/local/java/jdk-16.0.1/bin/java" 1
sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/local/java/jdk-16.0.1/bin/javac" 1

# You should still run these
sudo update-alternatives --config java
sudo update-alternatives --config javac
#+END_SRC

Also add the following line to ~.bashrc~:

#+BEGIN_SRC bash
export JAVA_HOME="/usr/lib/jvm/java-openjdk" # Should be a soft link managed by alternatives
#+END_SRC

*** Install maven

https://tecadmin.net/install-apache-maven-on-fedora/

Download, extract and create softlink for maven

#+BEGIN_SRC bash
cd /opt
sudo wget https://www-us.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
sudo tar xzf apache-maven-3.8.1-bin.tar.gz
sudo ln -s apache-maven-3.8.1 maven
#+END_SRC

Then add to your ~.bashrc~ file:

#+BEGIN_SRC bash
export M2_HOME="/opt/maven"
PATH="$PATH":"$M2_HOME/bin"
#+END_SRC

*** IntelliJ

[[https://technoref.wordpress.com/2016/01/19/install-idea-intellij-in-fedora-23/]]

The desktop laucher file should be placed in
~/usr/share/applications/idea.desktop~, not in ~$HOME/Desktop~.

** Visual Studio code

[[https://fedoramagazine.org/using-visual-studio-code-fedora/]]

** Teams

https://docs.microsoft.com/en-us/answers/questions/3746/provide-repository-installation-instructions-inste.html

** Slack

https://slack.com/intl/en-se/help/articles/212924728-Download-Slack-for-Linux--beta-#fedora-2

** Discord

Install discord by downloading the ~.tar.gz~ file and untar it. https://discord.com/api/download?platform=linux&format=tar.gz

Install ~libatomic~ or you will have microphone problems! From
https://www.reddit.com/r/discordapp/comments/7euehr/need_some_help_with_my_installation_on_linux/

#+BEGIN_SRC bash
cd /opt
sudo wget --content-disposition "https://discord.com/api/download?platform=linux&format=tar.gz"
sudo tar xzf discord-0.*.tar.gz
sudo dnf install libatomic
#+END_SRC

** Nvidia drivers

https://linuxconfig.org/how-to-install-the-nvidia-drivers-on-fedora-32 (tried on v 34 as well)

Open up the terminal and identify your Nvidia graphic card model by executing:

#+BEGIN_SRC bash
lspci -vnn | grep VGA
 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM204 [GeForce GTX 970] [10de:13c2] (rev a1) (prog-if 00 [VGA controller])
#+END_SRC

Fully update your system.

#+BEGIN_SRC bash
sudo dnf update
#+END_SRC

Failing to fully update your system may result in a kernel version mismatch
producing the "NVIDIA kernel module missing. Falling back to nouveau." error
message after the nvidia driver installation and system reboot.

Enable RPM fusion:

#+BEGIN_SRC bash
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm 
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
#+END_SRC

Install drivers. This works for GeForce GTX 970:

#+BEGIN_SRC bash
sudo dnf install akmod-nvidia
#+END_SRC

Reboot system

#+BEGIN_SRC bash
sudo reboot
#+END_SRC

After boot, check the version for the installed kernel module:

#+BEGIN_SRC bash
modinfo -F version nvidia
# As long as it finds something we should be fine
#+END_SRC
