set -g prefix C-a
unbind C-b
bind C-a send-prefix

# https://schauderbasis.de/posts/hide_tmux_status_bar_if_its_not_needed/
# only show status bar if there is more then one window
set -g status off
set-hook -g after-new-window      'if "[ #{session_windows} -gt 1 ]" "set status on"'
set-hook -g after-kill-pane       'if "[ #{session_windows} -lt 2 ]" "set status off"'
set-hook -g pane-exited           'if "[ #{session_windows} -lt 2 ]" "set status off"'
set-hook -g window-layout-changed 'if "[ #{session_windows} -lt 2 ]" "set status off"'

# Only display the windows in the status bar
set -g status-right ''
set -g status-left ''

# Hide the floating window with "bind Enter"
set-option -s escape-time 0
#bind -n Escape detach-client
bind Enter detach-client

# start window indexing at one instead of zero
set-option -g base-index 1
set-option -g renumber-windows on

set-option -wg window-status-separator " | "

# Load color theme
source-file ~/.config/tmux/tmux-colors.conf
