(deftheme mywombat2
  "Created 2017-10-01.")

(custom-theme-set-variables
 'mywombat2
 '(ansi-color-names-vector ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"]))

(custom-theme-set-faces
 'mywombat2
 '(cursor ((t (:background "#f6f3e8"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#303030"))))
 '(highlight ((t (:background "#454545"))))
 '(region ((t (:background "#eea9b8" :foreground "#262626"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#333366" :foreground "#f6f3e8"))))
 '(isearch ((t (:background "#ff8700" :foreground "#080808"))))
 '(lazy-highlight ((t (:background "#ffff00" :foreground "#080808"))))
 '(mode-line ((t (:background "#f6f3e8" :foreground "#444444"))))
 '(mode-line-inactive ((t (:background "#444444" :foreground "#f6f3e8"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(font-lock-type-face ((t (:foreground "#92a65e" :weight bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline t))))
 '(button ((t (:inherit (link)))))
 '(header-line ((((class color) (min-colors 89)) (:background "#303030" :foreground "#e7f6da"))))
 '(show-paren-match ((t (:background "#ff8700" :foreground "#080808"))))
 '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 '(org-block ((t (:background "#1c1c1c"))))
 '(org-block-begin-line ((t (:background "#92a65e" :foreground "#262626"))))
 '(org-block-end-line ((t (:inherit (org-block-begin-line)))))
 '(default ((((class color) (min-colors 89)) (:background "#242424" :foreground "#f6f3e8"))))
 '(company-tooltip ((t (:inherit (mode-line-inactive)))))
 '(company-tooltip-selection ((t (:inherit (region)))))
 '(company-tooltip-annotation ((t (:foreground "#8ac6f2"))))
 '(company-tooltip-common ((t (:foreground "#cae682"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#000080"))))
 '(company-tooltip-common-selection ((t (:foreground "#8b0000")))))

(provide-theme 'mywombat2)
