#!/bin/bash

NEED_UNSTASH=false

git rev-parse --is-inside-work-tree > /dev/null 2>&1

if [ $? -ne 0 ]; then
  echo "Current directory is not a git repository. Exiting..." 1>&2
  exit 128
fi

git diff-index --quiet HEAD --

if [ $? -ne 0 ]; then
  git stash --quiet
  NEED_UNSTASH=true
  echo stashing
fi

echo start
git status
echo end

if [ "$NEED_UNSTASH" = "true" ]; then
  git stash pop --quiet
  echo unstashing
fi
