#!/bin/bash

RESULT_DIR="$HOME/remote-ssh"
FILE_PREFIX="prefix"
# Replace this variable with the command to be run on the remote server
COMMAND='ls'

if [[ "$#" -ne 1 || "$1" = '-h' ]]
  then
    cat 1>&2 << END_HEREDOC
Description

Usage:
  $(basename "$0") params
END_HEREDOC
    exit 1
fi

mkdir -p "$RESULT_DIR"

TMP_FILE=$(mktemp -p "$RESULT_DIR")

# Replace this part with the actual ssh command
ssh $1 "hostname; $COMMAND" > "$TMP_FILE"

REMOTE_HOST_NAME=$(head -n1 "$TMP_FILE")

sed -i '1d' "$TMP_FILE"

DATE_STRING=$(date '+%y_%m_%d__%H_%M_%S')

RESULT_FILE="${RESULT_DIR}/${FILE_PREFIX}_${DATE_STRING}_${REMOTE_HOST_NAME}.txt"

mv "$TMP_FILE" "$RESULT_FILE"
