#!/bin/sh

sxhkd &

####################
# Monitor settings #
####################
#bspc monitor -d I II III IV V VI VII VIII IX X
# You find the monitor names by running "xrandr"
bspc monitor DVI-D-0 -d I II III IV V
bspc monitor DVI-I-0 -d VI VII VIII IX X

###################
# Border settings #
###################
bspc config border_width         8
bspc config window_gap           12
bspc config normal_border_color  "#333333"
bspc config active border_color  "#FF0000"
bspc config focused_border_color "#008800"

##################
# Mouse settings #
##################
bspc config click_to_focus       true




bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
