#!/bin/bash

# Need to install tesseract and ImageMagick

SCR="$HOME/screen_to_text_tmp"
TES_LANG_OPT=""

usage() {
  cat 1>&2 << END_HEREDOC
Description
  Mark a box of text which you want the text from. If you specify a
  language, that langauge needs to be installed for tesseract.

  Temporary files will be created at (there is no automatic clean
  up but you can remove them whenever you want):
  - $SCR.png
  - $SCR.txt

Usage:
  $(basename $0)
  $(basename $0) <lang>
END_HEREDOC
}

if [[ "$#" -gt 1 ]]; then
  usage
  exit 1
elif [[ "$#" -eq 1 ]]; then
  if [[ "$1" = "-h" ]]; then
    usage
    exit 1
  fi
  if ! tesseract --list-langs | grep -Eq "^$1$"; then
    echo "'$1' is not among the installed languages for tesseract" 1>&2
    tesseract --list-langs 1>&2
    exit 2
  fi
  TES_LANG_OPT="-l $1"
fi

gnome-screenshot -a -f $SCR.png

mogrify -modulate 100,0 -resize 400% $SCR.png
#should increase detection rate

tesseract $TES_LANG_OPT $SCR.png $SCR &> /dev/null

cat $SCR.txt
cat $SCR.txt | xclip
