#!/bin/bash

# Need to install tesseract and ImageMagick

SRC="/tmp/screen_to_text_tmp"
TES_LANG_OPT=""
TAKE_SCREENSHOT="TRUE"

usage() {
  cat 1>&2 << END_HEREDOC
Description
  Mark a box of text which you want the text from. If you specify a
  language, that langauge needs to be installed for tesseract.

  Temporary files will be created at:
  - $SRC.png
  - $SRC.txt

Usage:
  $(basename $0) [options]

Options:
  -h:
    Show this help
  -l <lang>:
    Use <lang> as language in tesseract
  -w <line-width>:
    Format the output in lines of length <line-width>
  -n:
    Don't take a new screen shot. Use the previous one
END_HEREDOC
}

while getopts ":l:w:hn" opt; do
  case $opt in
    l)
      if ! tesseract --list-langs | grep -Eq "^${OPTARG}$"; then
        echo "'$OPTARG' is not among the installed languages for tesseract" 1>&2
        tesseract --list-langs 1>&2
        exit 2
      fi
      TES_LANG_OPT="-l $OPTARG"
      ;;
    w)
      if ! [[ "$OPTARG" =~ ^[0-9]+$ ]]; then
        echo "'$OPTARG' is not a valid number. Use -h for usage"
        exit 1
      fi
      WIDTH="$OPTARG"
      ;;
    h)
      usage
      exit 1
      ;;
    n)
      TAKE_SCREENSHOT="FALSE"
      ;;
    \?)
      # Unknown option
      echo "Invalid option: -$OPTARG. Use -h for usage" >&2
      exit 1
      ;;
    :)
      # Argument missing. The option expects an argument
      echo "Option -$OPTARG requires an argument. Use -h for usage" >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

if [ "$TAKE_SCREENSHOT" = "TRUE" ]; then
  gnome-screenshot -a -f $SRC.png

  # To increase the detection rate we will first make the image bigger
  mogrify -modulate 100,0 -resize 400% $SRC.png
  # And then make it sharper
  convert $SRC.png -sharpen 0x3 $SRC.png
fi

tesseract $TES_LANG_OPT $SRC.png $SRC &> /dev/null

sed -r -i\
 "s/\$3/S3/g
  s/lf/If/g
  s/\|/I/g
  # Removes form feed character that tesseract sometimes adds
  s/\x0c//
  s/—/-/g
  s/[“”]/\"/g
  s/[’]/'/g
  s/^[-e>«»\*¢©]+ /- /"\
  $SRC.txt # Removes form feed character that tesseract sometimes adds

if [ -z "${WIDTH+x}" ]; then
  OUTPUT=$(cat $SRC.txt)
else
  OUTPUT=$(cat $SRC.txt | tr '\n' ' ' | sed -r 's/  +/ /g' | fold -s -w$WIDTH | sed -r 's/ *$//g')
fi

echo "$OUTPUT"
echo "$OUTPUT" | xclip
